vim.keymap.set("i", "(", "(", { buffer = true })
vim.keymap.set("i", "[", "[", { buffer = true })
vim.keymap.set("i", "{", "{", { buffer = true })
vim.keymap.set("i", "\"", "\"", { buffer = true })
vim.keymap.set("i", "'", "'", { buffer = true })
vim.keymap.set("i", "`", "`", { buffer = true })
